export const SEED_JOBS = [
  {
    title: 'Full Stack Engineer',
    company: 'Harbor Labs',
    location: 'San Francisco, CA',
    remote: 'hybrid',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/harbor-labs-fullstack',
    department: 'Engineering',
    seniority: 'mid',
    skills_csv: 'javascript, typescript, react, node.js, postgres, aws, docker',
    posted_at: '2026-08-18',
    description:
      'Harbor Labs is hiring a full stack engineer to ship candidate-facing product. You will work across React, Node.js, and Postgres with a small team.',
    requirements:
      '3+ years building web apps. TypeScript, React, Node.js, relational SQL, and comfort with AWS and Docker. Clear written communication.',
  },
  {
    title: 'Senior Frontend Engineer',
    company: 'Northwind Health',
    location: 'Remote, US',
    remote: 'remote',
    source: 'lever',
    source_url: 'https://example.com/jobs/northwind-frontend',
    department: 'Engineering',
    seniority: 'senior',
    skills_csv: 'react, typescript, css, accessibility, jest, graphql',
    posted_at: '2026-08-20',
    description:
      'Own the patient portal UI. We care about accessibility, performance, and calm design more than novelty.',
    requirements:
      '5+ years of React and TypeScript. Strong CSS, accessibility, and testing with Jest. GraphQL experience is a plus.',
  },
  {
    title: 'Backend Engineer, Node.js',
    company: 'Parcelly',
    location: 'Austin, TX',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/parcelly-backend',
    department: 'Engineering',
    seniority: 'mid',
    skills_csv: 'node.js, express, postgres, redis, kafka, docker, aws',
    posted_at: '2026-08-12',
    description:
      'Build APIs for a logistics network. High-volume writes, clear contracts, and boring reliability.',
    requirements:
      'Node.js, Express, Postgres, Redis. Experience with queues or Kafka. Docker and AWS basics.',
  },
  {
    title: 'Data Analyst',
    company: 'Civic Metrics',
    location: 'Washington, DC',
    remote: 'hybrid',
    source: 'lever',
    source_url: 'https://example.com/jobs/civic-metrics-analyst',
    department: 'Analytics',
    seniority: 'mid',
    skills_csv: 'sql, tableau, excel, python, pandas, data analysis, statistics',
    posted_at: '2026-08-21',
    description:
      'Turn messy public-sector data into dashboards leadership will actually use. Partner with program managers.',
    requirements:
      'SQL, Tableau or Power BI, Excel, and enough Python/pandas to clean datasets. Clear storytelling.',
  },
  {
    title: 'Analytics Engineer',
    company: 'Lumen Retail',
    location: 'Chicago, IL',
    remote: 'remote',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/lumen-analytics-engineer',
    department: 'Data',
    seniority: 'mid',
    skills_csv: 'dbt, snowflake, sql, python, airflow, data modeling',
    posted_at: '2026-08-15',
    description:
      'Model the warehouse so marketing and finance share one set of numbers. dbt on Snowflake.',
    requirements:
      'dbt, Snowflake or BigQuery, SQL, and data modeling. Airflow or similar orchestration is a plus.',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'Kepler Vision',
    location: 'Seattle, WA',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/kepler-ml',
    department: 'ML',
    seniority: 'senior',
    skills_csv: 'python, pytorch, tensorflow, aws, docker, machine learning, nlp',
    posted_at: '2026-08-10',
    description:
      'Ship ranking and NLP models into production, not notebooks. You will own training, eval, and inference.',
    requirements:
      'Python, PyTorch or TensorFlow, production ML, Docker, and AWS. NLP or LLM fine-tuning is welcome.',
  },
  {
    title: 'Product Manager',
    company: 'Open Ledger',
    location: 'New York, NY',
    remote: 'hybrid',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/open-ledger-pm',
    department: 'Product',
    seniority: 'senior',
    skills_csv: 'product management, roadmap, agile, sql, stakeholder management, a/b testing',
    posted_at: '2026-08-19',
    description:
      'Own onboarding for a B2B finance product. Write specs, cut scope, and measure activation.',
    requirements:
      '4+ years product management, roadmap ownership, stakeholder management, and comfort with SQL and A/B tests.',
  },
  {
    title: 'UX Designer',
    company: 'Kindred Clinics',
    location: 'Remote, US',
    remote: 'remote',
    source: 'lever',
    source_url: 'https://example.com/jobs/kindred-ux',
    department: 'Design',
    seniority: 'mid',
    skills_csv: 'figma, user research, ux, ui, wireframing, accessibility',
    posted_at: '2026-08-22',
    description:
      'Design clinical workflows that nurses will not hate. Research with real staff, then ship in Figma.',
    requirements:
      'Figma, user research, UX/UI, wireframing, and accessibility. Healthcare or complex-form experience helps.',
  },
  {
    title: 'Customer Success Manager',
    company: 'Nimbus HR',
    location: 'Denver, CO',
    remote: 'remote',
    source: 'company',
    source_url: 'https://example.com/jobs/nimbus-csm',
    department: 'Customer Success',
    seniority: 'mid',
    skills_csv: 'customer success, account management, salesforce, onboarding, communication',
    posted_at: '2026-08-17',
    description:
      'Keep mid-market HR teams healthy after go-live. Own onboarding, QBR, and expansion signals.',
    requirements:
      'Customer success or account management, Salesforce, and calm written communication. HRIS familiarity is a plus.',
  },
  {
    title: 'Enterprise Account Executive',
    company: 'Stackline Security',
    location: 'Boston, MA',
    remote: 'hybrid',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/stackline-ae',
    department: 'Sales',
    seniority: 'senior',
    skills_csv: 'enterprise sales, b2b, negotiation, pipeline, salesforce, communication',
    posted_at: '2026-08-11',
    description:
      'Full-cycle enterprise sales for a security product. You will build pipeline and close with security buyers.',
    requirements:
      'Enterprise B2B sales, negotiation, pipeline hygiene in Salesforce. Security or SaaS background preferred.',
  },
  {
    title: 'Sales Development Representative',
    company: 'Brightpath Ed',
    location: 'Remote, US',
    remote: 'remote',
    source: 'indeed',
    source_url: 'https://example.com/jobs/brightpath-sdr',
    department: 'Sales',
    seniority: 'entry',
    skills_csv: 'sdr, b2b, cold calling, hubspot, communication, pipeline',
    posted_at: '2026-08-23',
    description:
      'Open conversations with school-district buyers. High activity, real coaching, and a path to AE.',
    requirements:
      'Comfort with cold calling, HubSpot or similar, and written outreach. New grads welcome.',
  },
  {
    title: 'Digital Marketing Manager',
    company: 'Field & Grain',
    location: 'Portland, OR',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/fieldgrain-marketing',
    department: 'Marketing',
    seniority: 'mid',
    skills_csv: 'seo, sem, google analytics, content strategy, copywriting, a/b testing',
    posted_at: '2026-08-14',
    description:
      'Grow a CPG brand with search, content, and honest measurement. No vanity metrics.',
    requirements:
      'SEO, SEM, Google Analytics, content strategy, and A/B testing. Copy you are proud to ship.',
  },
  {
    title: 'Content Strategist',
    company: 'Atlas Learning',
    location: 'Remote, US',
    remote: 'remote',
    source: 'lever',
    source_url: 'https://example.com/jobs/atlas-content',
    department: 'Marketing',
    seniority: 'mid',
    skills_csv: 'content strategy, copywriting, seo, communication, documentation',
    posted_at: '2026-08-09',
    description:
      'Own the editorial system for a learning product. Brief writers, set voice, and connect content to SEO.',
    requirements:
      'Content strategy, copywriting, SEO, and cross-functional communication.',
  },
  {
    title: 'Recruiter, Technical',
    company: 'OpenPath Staffing',
    location: 'Remote, US',
    remote: 'remote',
    source: 'company',
    source_url: '/#/matches',
    department: 'Talent',
    seniority: 'mid',
    skills_csv: 'recruiting, sourcing, interviewing, communication, greenhouse, stakeholder management',
    posted_at: '2026-08-24',
    description:
      'Join OpenPath. Source and close engineers and analysts for partner companies. Candidate-first, no ghosting.',
    requirements:
      'Technical recruiting or sourcing, structured interviewing, and clear updates to candidates and hiring managers.',
  },
  {
    title: 'HR Generalist',
    company: 'Mapleworks',
    location: 'Minneapolis, MN',
    remote: 'onsite',
    source: 'indeed',
    source_url: 'https://example.com/jobs/mapleworks-hr',
    department: 'People',
    seniority: 'mid',
    skills_csv: 'hris, onboarding, workday, payroll, communication, employee relations',
    posted_at: '2026-08-13',
    description:
      'Support a 400-person manufacturer through onboarding, questions, and fair process.',
    requirements:
      'HRIS (Workday or similar), onboarding, payroll coordination, and employee relations judgment.',
  },
  {
    title: 'Staff Accountant',
    company: 'Harborpoint Credit',
    location: 'Charlotte, NC',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/harborpoint-accountant',
    department: 'Finance',
    seniority: 'mid',
    skills_csv: 'accounting, gaap, excel, financial modeling, audit, netsuite',
    posted_at: '2026-08-16',
    description:
      'Close the books, support audit, and keep NetSuite clean. Close calendar is real, not theatrical.',
    requirements:
      'GAAP accounting, Excel, audit support, and an ERP such as NetSuite or Oracle.',
  },
  {
    title: 'Financial Analyst',
    company: 'Orbit Mobility',
    location: 'Los Angeles, CA',
    remote: 'hybrid',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/orbit-fpna',
    department: 'Finance',
    seniority: 'mid',
    skills_csv: 'financial modeling, excel, forecasting, sql, powerpoint, stakeholder management',
    posted_at: '2026-08-08',
    description:
      'FP&A for a mobility startup. Forecast, explain variance, and partner with ops leads.',
    requirements:
      'Financial modeling, Excel, forecasting, and enough SQL to pull your own data.',
  },
  {
    title: 'Registered Nurse, Care Coordination',
    company: 'Bayview Medical Group',
    location: 'Oakland, CA',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/bayview-rn',
    department: 'Clinical',
    seniority: 'mid',
    skills_csv: 'nursing, case management, ehr, epic, hipaa, patient care',
    posted_at: '2026-08-21',
    description:
      'Coordinate care for complex adults. You will live in Epic and on the phone with patients.',
    requirements:
      'RN license, case management or clinic experience, Epic or similar EHR, HIPAA, and patient care judgment.',
  },
  {
    title: 'Operations Manager',
    company: 'Redwood Fulfillment',
    location: 'Stockton, CA',
    remote: 'onsite',
    source: 'indeed',
    source_url: 'https://example.com/jobs/redwood-ops',
    department: 'Operations',
    seniority: 'senior',
    skills_csv: 'operations, logistics, inventory, lean, leadership, sap',
    posted_at: '2026-08-07',
    description:
      'Run a shift in a regional warehouse. Safety, throughput, and people who stay.',
    requirements:
      'Operations or logistics leadership, inventory, lean ideas, and ERP exposure (SAP or similar).',
  },
  {
    title: 'Supply Chain Analyst',
    company: 'Helios Foods',
    location: 'Dallas, TX',
    remote: 'hybrid',
    source: 'lever',
    source_url: 'https://example.com/jobs/helios-supply',
    department: 'Supply Chain',
    seniority: 'mid',
    skills_csv: 'supply chain, excel, sql, inventory, forecasting, sap',
    posted_at: '2026-08-18',
    description:
      'Improve forecast accuracy and inventory turns. You will model, then walk the floor.',
    requirements:
      'Supply chain analysis, Excel, SQL, inventory, and forecasting. SAP is a plus.',
  },
  {
    title: 'QA Engineer',
    company: 'Pilot Pay',
    location: 'Remote, US',
    remote: 'remote',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/pilotpay-qa',
    department: 'Engineering',
    seniority: 'mid',
    skills_csv: 'qa, playwright, cypress, javascript, ci/cd, selenium',
    posted_at: '2026-08-20',
    description:
      'Automate the money path. You will write Playwright tests and keep CI honest.',
    requirements:
      'QA automation with Playwright or Cypress, JavaScript, and CI/CD. Selenium history is fine.',
  },
  {
    title: 'DevOps Engineer',
    company: 'Cedar Cloud',
    location: 'Raleigh, NC',
    remote: 'hybrid',
    source: 'company',
    source_url: 'https://example.com/jobs/cedar-devops',
    department: 'Platform',
    seniority: 'mid',
    skills_csv: 'aws, terraform, kubernetes, docker, ci/cd, linux, github actions',
    posted_at: '2026-08-12',
    description:
      'Keep clusters boring and deploys reversible. Terraform, Kubernetes, and GitHub Actions.',
    requirements:
      'AWS, Terraform, Kubernetes, Docker, Linux, and CI/CD. On-call is shared and paid.',
  },
  {
    title: 'iOS Engineer',
    company: 'Trailhead Fitness',
    location: 'Boulder, CO',
    remote: 'hybrid',
    source: 'lever',
    source_url: 'https://example.com/jobs/trailhead-ios',
    department: 'Mobile',
    seniority: 'mid',
    skills_csv: 'swift, ios, mobile, rest, git, accessibility',
    posted_at: '2026-08-15',
    description:
      'Ship Swift features for a workout app used daily. Offline-first and accessible.',
    requirements:
      'Swift, iOS, REST APIs, Git, and accessibility. 3+ years of shipped App Store work.',
  },
  {
    title: 'Android Engineer',
    company: 'Trailhead Fitness',
    location: 'Boulder, CO',
    remote: 'hybrid',
    source: 'lever',
    source_url: 'https://example.com/jobs/trailhead-android',
    department: 'Mobile',
    seniority: 'mid',
    skills_csv: 'kotlin, android, mobile, rest, git, java',
    posted_at: '2026-08-15',
    description:
      'Kotlin Android app in lockstep with iOS. We care about battery, crash-free sessions, and clean architecture.',
    requirements:
      'Kotlin, Android, REST, Git. Java history is welcome. 3+ years shipping Play Store apps.',
  },
  {
    title: 'Business Operations Associate',
    company: 'OpenPath Staffing',
    location: 'Remote, US',
    remote: 'remote',
    source: 'company',
    source_url: '/#/about',
    department: 'Operations',
    seniority: 'entry',
    skills_csv: 'excel, operations, communication, documentation, project management, salesforce',
    posted_at: '2026-08-25',
    description:
      'Help OpenPath keep candidate pipelines tidy. Spreadsheets, follow-ups, and process that respects people.',
    requirements:
      'Excel, written communication, documentation, and comfort with a CRM. Early career welcome.',
  },
  {
    title: 'Project Manager',
    company: 'Quay Systems',
    location: 'Atlanta, GA',
    remote: 'hybrid',
    source: 'indeed',
    source_url: 'https://example.com/jobs/quay-pm',
    department: 'Delivery',
    seniority: 'mid',
    skills_csv: 'project management, agile, jira, stakeholder management, communication, budgeting',
    posted_at: '2026-08-11',
    description:
      'Run implementation projects for a workflow product. Dates, risks, and humans in Jira.',
    requirements:
      'Project management, Agile, Jira, stakeholder management, and basic budgeting.',
  },
  {
    title: 'IT Support Specialist',
    company: 'Lakeside Credit Union',
    location: 'Cleveland, OH',
    remote: 'onsite',
    source: 'company',
    source_url: 'https://example.com/jobs/lakeside-it',
    department: 'IT',
    seniority: 'entry',
    skills_csv: 'windows, okta, sso, documentation, communication, security',
    posted_at: '2026-08-19',
    description:
      'Help 900 employees with laptops, SSO, and calm tickets. Security-aware, not script-only.',
    requirements:
      'Windows support, identity tools such as Okta/SSO, documentation, and patient communication.',
  },
  {
    title: 'Python Engineer',
    company: 'Fathom Research',
    location: 'Remote, US',
    remote: 'remote',
    source: 'wellfound',
    source_url: 'https://example.com/jobs/fathom-python',
    department: 'Engineering',
    seniority: 'mid',
    skills_csv: 'python, fastapi, postgres, docker, pytest, aws, etl',
    posted_at: '2026-08-22',
    description:
      'Build research data APIs in Python. FastAPI, Postgres, tests, and small ETL jobs.',
    requirements:
      'Python, FastAPI or Django, Postgres, Docker, pytest. AWS and ETL experience help.',
  },
  {
    title: 'Java Engineer',
    company: 'Clearwater Banking',
    location: 'Jacksonville, FL',
    remote: 'hybrid',
    source: 'greenhouse',
    source_url: 'https://example.com/jobs/clearwater-java',
    department: 'Engineering',
    seniority: 'mid',
    skills_csv: 'java, spring, postgres, kafka, kubernetes, sql',
    posted_at: '2026-08-06',
    description:
      'Payments services in Java/Spring. Correctness over cleverness. Kafka and Kubernetes in production.',
    requirements:
      'Java, Spring, SQL, and distributed systems basics. Kafka and Kubernetes preferred.',
  },
  {
    title: 'Security Analyst',
    company: 'Municipal Cloud',
    location: 'Phoenix, AZ',
    remote: 'hybrid',
    source: 'usajobs',
    source_url: 'https://example.com/jobs/municipal-security',
    department: 'Security',
    seniority: 'mid',
    skills_csv: 'security, siem, python, linux, incident response, documentation',
    posted_at: '2026-08-14',
    description:
      'Watch city systems, triage alerts, and write reports humans can act on.',
    requirements:
      'Security operations, SIEM, Linux, and incident response. Python scripting is a plus. Public-sector interest welcome.',
  },
  {
    title: 'Executive Assistant',
    company: 'OpenPath Staffing',
    location: 'San Jose, CA',
    remote: 'hybrid',
    source: 'company',
    source_url: '/#/about',
    department: 'Office',
    seniority: 'mid',
    skills_csv: 'communication, calendar, documentation, stakeholder management, excel',
    posted_at: '2026-08-23',
    description:
      'Support the founding team. Calendar, candidate travel, and a high bar for discretion.',
    requirements:
      'Executive support, calendar mastery, documentation, and Excel. Staffing or recruiting office experience helps.',
  },
  {
    title: 'Customer Support Specialist',
    company: 'Parcelly',
    location: 'Remote, US',
    remote: 'remote',
    source: 'indeed',
    source_url: 'https://example.com/jobs/parcelly-support',
    department: 'Support',
    seniority: 'entry',
    skills_csv: 'zendesk, communication, customer success, documentation, excel',
    posted_at: '2026-08-24',
    description:
      'Help shippers when a label breaks. Zendesk, clear writing, and follow-through.',
    requirements:
      'Customer support, Zendesk or similar, and written English. Logistics curiosity is a plus.',
  },
]
